spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql:
        format_sql: false # 배포 시 false로 설정
  mail:
    host: smtp.gmail.com
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging.level:
  root: info
#  org.hibernate.SQL: debug
# 배포시 hibernate.SQL 주석처리

openvidu:
  url:
  secret:

secret:

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static:
    stack:
      auto: false